const CACHE_KEY = '@europeana:portal.js:collections:topics';
const ENTITY_TYPE = 'concept';
const FEATURED = [
  'http://data.europeana.eu/concept/base/106',
  'http://data.europeana.eu/concept/base/112',
  'http://data.europeana.eu/concept/base/113',
  'http://data.europeana.eu/concept/base/114',
  'http://data.europeana.eu/concept/base/1146',
  'http://data.europeana.eu/concept/base/120',
  'http://data.europeana.eu/concept/base/124',
  'http://data.europeana.eu/concept/base/14',
  'http://data.europeana.eu/concept/base/1409',
  'http://data.europeana.eu/concept/base/15',
  'http://data.europeana.eu/concept/base/1594',
  'http://data.europeana.eu/concept/base/1600',
  'http://data.europeana.eu/concept/base/1603',
  'http://data.europeana.eu/concept/base/1618',
  'http://data.europeana.eu/concept/base/1645',
  'http://data.europeana.eu/concept/base/1647',
  'http://data.europeana.eu/concept/base/1653',
  'http://data.europeana.eu/concept/base/1654',
  'http://data.europeana.eu/concept/base/1659',
  'http://data.europeana.eu/concept/base/1664',
  'http://data.europeana.eu/concept/base/1665',
  'http://data.europeana.eu/concept/base/1668',
  'http://data.europeana.eu/concept/base/167',
  'http://data.europeana.eu/concept/base/1672',
  'http://data.europeana.eu/concept/base/1673',
  'http://data.europeana.eu/concept/base/17',
  'http://data.europeana.eu/concept/base/1700',
  'http://data.europeana.eu/concept/base/1705',
  'http://data.europeana.eu/concept/base/1710',
  'http://data.europeana.eu/concept/base/1719',
  'http://data.europeana.eu/concept/base/1720',
  'http://data.europeana.eu/concept/base/18',
  'http://data.europeana.eu/concept/base/187',
  'http://data.europeana.eu/concept/base/19',
  'http://data.europeana.eu/concept/base/190',
  'http://data.europeana.eu/concept/base/194',
  'http://data.europeana.eu/concept/base/23',
  'http://data.europeana.eu/concept/base/235',
  'http://data.europeana.eu/concept/base/236',
  'http://data.europeana.eu/concept/base/237',
  'http://data.europeana.eu/concept/base/238',
  'http://data.europeana.eu/concept/base/24',
  'http://data.europeana.eu/concept/base/247',
  'http://data.europeana.eu/concept/base/258',
  'http://data.europeana.eu/concept/base/277',
  'http://data.europeana.eu/concept/base/29',
  'http://data.europeana.eu/concept/base/30',
  'http://data.europeana.eu/concept/base/31',
  'http://data.europeana.eu/concept/base/321',
  'http://data.europeana.eu/concept/base/33',
  'http://data.europeana.eu/concept/base/35',
  'http://data.europeana.eu/concept/base/37',
  'http://data.europeana.eu/concept/base/41',
  'http://data.europeana.eu/concept/base/43',
  'http://data.europeana.eu/concept/base/46',
  'http://data.europeana.eu/concept/base/47',
  'http://data.europeana.eu/concept/base/48',
  'http://data.europeana.eu/concept/base/49',
  'http://data.europeana.eu/concept/base/50',
  'http://data.europeana.eu/concept/base/51',
  'http://data.europeana.eu/concept/base/52',
  'http://data.europeana.eu/concept/base/54',
  'http://data.europeana.eu/concept/base/56',
  'http://data.europeana.eu/concept/base/59',
  'http://data.europeana.eu/concept/base/6',
  'http://data.europeana.eu/concept/base/60',
  'http://data.europeana.eu/concept/base/61',
  'http://data.europeana.eu/concept/base/62',
  'http://data.europeana.eu/concept/base/74',
  'http://data.europeana.eu/concept/base/744',
  'http://data.europeana.eu/concept/base/79',
  'http://data.europeana.eu/concept/base/80',
  'http://data.europeana.eu/concept/base/84',
  'http://data.europeana.eu/concept/base/86'
];

import baseData from './index.js';

const data = (config = {}) => baseData(ENTITY_TYPE, config);

export {
  data,
  CACHE_KEY,
  ENTITY_TYPE,
  FEATURED
};
