version: "3.8"
services:
  keycloak:
    image: keycloak
    build:
      context: ../..
      dockerfile: ./packages/keycloak-theme/Dockerfile
    volumes:
      - type: bind
        source: ./theme
        target: /opt/keycloak/themes/europeana
    ports:
      - "10001:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD
  smtp:
    image: namshi/smtp
    expose:
      - "25"
