apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: europeana/portal.js
  newTag: ${K8S_DEPLOYMENT_IMAGE_TAG}
namespace: production
resources:
- ../../base
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: portal-js
    spec:
      template:
        spec:
          containers:
            - name: portal-js-web
              resources:
                limits:
                  cpu: 450m
                  memory: 600Mi
                requests:
                  cpu: 300m
                  memory: 300Mi
