apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${K8S_RESOURCE_NAME}
  namespace: dev
  annotations:
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  ingressClassName: public-iks-k8s-nginx
  rules:
  - host: ${K8S_INGRESS_HOST}
    http:
      paths:
      - backend:
          service:
            name: ${K8S_RESOURCE_NAME}
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ${K8S_INGRESS_HOST}
    secretName: ${K8S_INGRESS_HOST}
