<template>
  <b-dropdown
    text="More filters"
    variant="light"
    no-caret
    class="more-facets position-static"
  >
    <strong
      class="mb-4 d-inline-block"
    >
      Image type
    </strong>
    <b-dropdown-form>
      <b-form-checkbox
        id="building"
        name="building"
        class="mb-3"
        plain
      >
        Building
        <span
          class="reset"
          aria-label="Close"
        >
          x
        </span>
      </b-form-checkbox>
      <b-form-checkbox
        id="inscription"
        name="inscription"
        class="mb-3"
        plain
      >
        Inscription
        <span
          class="reset"
          aria-label="Close"
        >
          x
        </span>
      </b-form-checkbox>
      <b-form-checkbox
        id="cartoon"
        name="cartoon"
        class="mb-3"
        plain
      >
        Cartoon
        <span
          class="reset"
          aria-label="Close"
        >
          x
        </span>
      </b-form-checkbox>
      <b-form-checkbox
        id="sculpture"
        name="sculpture"
        class="mb-3"
        plain
      >
        Sculpture
        <span
          class="reset"
          aria-label="Close"
        >
          x
        </span>
      </b-form-checkbox>
      <b-form-checkbox
        id="metalwork"
        name="metalwork"
        class="mb-3"
        plain
      >
        Metalwork
        <span
          class="reset"
          aria-label="Close"
        >
          x
        </span>
      </b-form-checkbox>
    </b-dropdown-form>
    <hr>
    <div
      class="float-right"
      role="group"
    >
      <button
        type="button"
        class="btn btn-link"
      >
        Cancel
      </button>
      <button
        type="button"
        class="btn btn-primary"
      >
        Apply
      </button>
    </div>
  </b-dropdown>
</template>
