apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: europeana/portal.js
  newTag: ${K8S_DEPLOYMENT_IMAGE_TAG}
namespace: preview
nameSuffix: ${K8S_RESOURCE_NAME_SUFFIX}
resources:
- ../../base
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/issuer: letsencrypt-production
      name: portal-js
