apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portal-js-env
spec:
  data:
    - remoteRef:
        key: k8s.dev.portal-js.CTF_CDA_ACCESS_TOKEN
      secretKey: CTF_CDA_ACCESS_TOKEN
    - remoteRef:
        key: k8s.dev.portal-js.CTF_CPA_ACCESS_TOKEN
      secretKey: CTF_CPA_ACCESS_TOKEN
    - remoteRef:
        key: k8s.dev.portal-js.EUROPEANA_API_KEY
      secretKey: EUROPEANA_API_KEY
    - remoteRef:
        key: k8s.dev.portal-js.EUROPEANA_API_KEY
      secretKey: EUROPEANA_API_KEY
    - remoteRef:
        key: k8s.dev.portal-js.REDIS_TLS_CA
      secretKey: REDIS_TLS_CA
    - remoteRef:
        key: k8s.dev.portal-js.REDIS_URL
      secretKey: REDIS_URL
    - remoteRef:
        key: username_password/k8s.dev.portal-js.JIRA_API_CREDENTIALS
        property: username
      secretKey: JIRA_API_USERNAME
    - remoteRef:
        key: username_password/k8s.dev.portal-js.JIRA_API_CREDENTIALS
        property: password
      secretKey: JIRA_API_PASSWORD
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ibm-cloud-secrets-manager-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: portal-js-env
