name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
      tag:
        description: Tag
        required: true
        default: master

jobs:
  # prep-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #

  kustomize:
    runs-on: ubuntu-latest
    # needs: [prep-env]
    environment: ${{ github.event.inputs.environment }}
    env:
      # DOCKER_IMAGE_TAG: ${{ needs.metadata.outputs.docker-full-tag }}
      CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}
      CTF_CPA_ACCESS_TOKEN: ${{ secrets.CTF_CPA_ACCESS_TOKEN }}
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      IBMCLOUD_API_URL: ${{ vars.IBMCLOUD_API_URL }}
      IBMCLOUD_CLUSTER_NAME: ${{ vars.IBMCLOUD_CLUSTER_NAME }}
      IBMCLOUD_REGION: ${{ vars.IBMCLOUD_REGION }}
      JIRA_API_PASSWORD: ${{ secrets.JIRA_API_PASSWORD }}
      JIRA_API_SERVICE_DESK_FEEDBACK_PASSWORD: ${{ secrets.JIRA_API_SERVICE_DESK_FEEDBACK_PASSWORD }}
      JIRA_API_SERVICE_DESK_FEEDBACK_USERNAME: ${{ secrets.JIRA_API_SERVICE_DESK_FEEDBACK_USERNAME }}
      JIRA_API_SERVICE_DESK_GALLERIES_PASSWORD: ${{ secrets.JIRA_API_SERVICE_DESK_GALLERIES_PASSWORD }}
      JIRA_API_SERVICE_DESK_GALLERIES_USERNAME: ${{ secrets.JIRA_API_SERVICE_DESK_GALLERIES_USERNAME }}
      JIRA_API_USERNAME: ${{ secrets.JIRA_API_USERNAME }}
      REDIS_TLS_CA: ${{ secrets.REDIS_TLS_CA }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install ibmcloud CLI
        # TODO: cache it
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-service
      -
        name: Login to IBM Cloud
        run: |
          ibmcloud login -a ${IBMCLOUD_API_URL} -r ${IBMCLOUD_REGION} --apikey ${IBMCLOUD_API_KEY}
          ibmcloud ks cluster config --cluster ${IBMCLOUD_CLUSTER_NAME}
