name: Docker images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: europeana/portal.js
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to DockerHub
        id: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Publish to NPM
        if: startsWith( github.event.ref, 'refs/tags/v' )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          docker run \
            --rm \
            --env NODE_AUTH_TOKEN=${NODE_AUTH_TOKEN} \
            --mount type=bind,source=$(pwd)/.github/workflows/support/docker-images/.npmrc,target=/root/.npmrc \
            --entrypoint npm ${{ steps.build-push.outputs.digest }} \
            publish --access public
      -
        name: Warm up jsDelivr
        if: startsWith( github.event.ref, 'refs/tags/v' )
        run: |
          # Give jsdelivr time to fetch the new version
          sleep 30
          docker run \
            --rm \
            --mount type=bind,source=$(pwd)/.github/workflows/support/docker-images/warm-up-jsdelivr.sh,target=/root/warm-up-jsdelivr.sh \
            --entrypoint /root/warm-up-jsdelivr.sh ${{ steps.build-push.outputs.digest }}
