name: Recycling

# TODO: ideally closing a PR would stop any runs of the ci workflow on the same
#       PR first.
# TODO: delete tagged images from Docker Hub

on:
  pull_request:
    types: closed

env:
  IBMCLOUD_API_URL: https://cloud.ibm.com
  IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
  IBMCLOUD_CLUSTER_NAME: europeana-web
  IBMCLOUD_REGION: eu-de

jobs:
  delete-ibm-cloud:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Prepare env for resource deletion, step 1
      run: echo "PULL_REQUEST_NUMBER=$(jq .pull_request.number ${GITHUB_EVENT_PATH})" >> $GITHUB_ENV
    -
      name: Prepare env for resource deletion, step 2
      run: echo "K8S_RESOURCE_NAME=portal-js-pr-${PULL_REQUEST_NUMBER}" >> $GITHUB_ENV
    -
      name: Install ibmcloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud plugin install container-service
    -
      name: Login to IBM Cloud
      run: |
        ibmcloud login -a ${IBMCLOUD_API_URL} -r ${IBMCLOUD_REGION} --apikey ${IBMCLOUD_API_KEY}
        ibmcloud ks cluster config --cluster ${IBMCLOUD_CLUSTER_NAME}
    -
      name: Delete from K8s
      run: |
        kubectl --namespace dev delete ingress/${K8S_RESOURCE_NAME}
        kubectl --namespace dev delete service/${K8S_RESOURCE_NAME}
        kubectl --namespace dev delete deployment/${K8S_RESOURCE_NAME}
