BEGIN;

  SET search_path TO events;

  CREATE TABLE web_element_event_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
  );

  CREATE INDEX ix_web_element_event_types_name ON events.web_element_event_types(name);

  INSERT INTO web_element_event_types (name) 
    SELECT DISTINCT activated_by
    FROM sessions
    WHERE activated_by IS NOT NULL
    ORDER BY activated_by ASC;

COMMIT;
