apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_RESOURCE_NAME}
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-dev-${K8S_RESOURCE_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-dev-${K8S_RESOURCE_NAME}
    spec:
      affinity: {}
      volumes:
        - name: nuxt-client-assets
          emptyDir: {}
      containers:
      - env:
        - name: PORTAL_BASE_URL
          value: https://${K8S_INGRESS_HOST}
        envFrom:
        - configMapRef:
            name: portal-js-env
            optional: false
        image: ${DOCKER_IMAGE_TAG}
        imagePullPolicy: Always
        name: portal-js-app
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_api/version
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 1m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: nuxt-client-assets
            mountPath: /app/packages/portal/.nuxt/dist/client
      - image: nginx:stable-alpine
        imagePullPolicy: Always
        name: portal-js-nginx
        ports:
          - containerPort: 80
            name: 80tcp
            protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 1m
            memory: 16Mi
        volumeMounts:
          - name: nuxt-client-assets
            mountPath: /usr/share/nginx/html/.nuxt
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
